AllCops:
  RunRailsCops: true

  Include:
    - '**/config.ru'
  Exclude:
    - '**/Rakefile'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'

Lint/AssignmentInCondition:
  Enabled: false

Documentation:
  Enabled: false
