notifications:
  webhooks:
    urls:
      - https://dockbit.com/webhooks/6ad7474fb9e86902f01e921b77e00adb1d2a6ff1
      - https://dockbit.com/webhooks/Q3mT5Fj2LGf5EMPCqYrg3xxn
    on_success: always
    on_failure: always
    on_start: never
